name: Pre-fill Pull Request
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install
      - run: |
          npm run all
  pre-fill-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Parsing branch name
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          ticket-base-url: 'https://trello.com/c/SMTbdsor'
          template-type: 'conventional'
          title-format: 'prefix(ticket): description'
          custom-template: >
            ### Description

            [ticket](ticketBaseUrl/ticket)

            ### Amazing changes

            prefix

            ### Description

            description

            ### Checklist

            - [ ] I have added/updated unit tests

            - [ ] I have added/updated documentation

            - [ ] I have updated the [CHANGELOG.md](./CHANGELOG.md) file
